### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by tsukoyumi** [brhaka/sfml-compiler#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [sfml-compiler](https://github.com/brhaka/sfml-compiler) package 1.3.4

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at Object.compile (/packages/sfml-compiler/lib/sfml-compiler.js:168:7)
    at /packages/sfml-compiler/lib/sfml-compiler.js:90:20)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:350265)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:348740)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:767067)
    at EventEmitter.t (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:774990)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -0:23.7.0 sfml-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
cpp-compiler 1.3.0 
file-icons 2.1.45 
gpp-compiler 3.0.7 
sfml-compiler 1.3.4 
```

**Comment by brhaka** [comment]
Fixed by @Kacarott (Release v1.3.5)
